/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Copper": "铜",
    "Discord": "Discord",
    "Donate": "Donate",
    "Enter": "进入",
    "Farming": "农业",
    "Food": "食物",
    "Gathering": "收集",
    "Iron": "铁",
    "Mining": "采矿",
    "Patreon": "Patreon",
    "Reddit": "Reddit",
    "Stone": "石头",
    "The": "",
    "The world of Theresmore awaits": "Theresmore 的世界在等待着你",
    "Tools": "工具",
    "Twitter": "Twitter",
    "Wood": "木头",
    "You need to enable JavaScript to run this game": "您需要启用 JavaScript 才能运行此游戏",
    "Your ancestors are well known for:": "您的祖先因以下原因而闻名：",
    "Your ancestors have mastered the best farming techniques and food will never be a problem for your people": "你的祖先掌握了最好的耕作技术，食物对你的人民来说永远不会成为问题",
    "Your ancestors knew how to refine metals and they used tools of rare workmanship": "你的祖先知道如何提炼金属，他们使用稀有工艺的工具",
    "Your ancestors knew the best places to cut good wood and dig the finest stone": "你的祖先知道最好的地方来砍伐优质木材和挖掘最好的石头",
    "Battery life": "电池寿命",
    "Battery Mode": "电池模式",
    "Close": "关闭",
    "Dark / Light mode": "深色 / 浅色 模式",
    "Difficulty Impossible": "难度 - 不可能",
    "Difficulty Normal": "难度 - 正常",
    "Difficulty Difficulty Hard": "难度 - 困难",
    "Hard reset": "硬重置",
    "Import from clipboard": "从剪贴板导入",
    "Performance": "性能",
    "Save to clipboard": "保存到剪贴板",
    "Save to file": "保存到文件",
    "Support": "支持",
    "You have to play more to get statistics": "你必须玩更多才能获得统计数据",
    "You have to work on it a bit": "你必须努力一点",
    "/s": "/秒",
    "Ancestor gathering": "祖传收集",
    "Build": "建造",
    "From nomadic hunters and gatherers, our people have grown up and are ready to settle in a fertile valley. From here will arise, perhaps, the greatest nation Theresmore has known. The age of man has just begun": "从游牧的猎人和采集者，我们的人民已经长大并准备在肥沃的山谷定居。 或许，热门所知道的最伟大的国家 Theresmore 将从这里兴起。 人类的时代才刚刚开始",
    "Housing": "住房",
    "Humans": "人类",
    "It's time to construct some dwellings": "是时候建造一些住宅了",
    "Research": "研究",
    "The beginning of human era": "人类时代的开始",
    "You have nothing to build": "你没有什么可建造的",
    "Your village is empty, look for some new technology": "你的村庄是空的，寻找一些新技术",
    "A small place to live": "一个可供居住的小地方",
    "Agriculture": "农业",
    "Common House": "普通房屋",
    "Gold": "黄金",
    "Humans:": "人类：",
    "Living Quarters": "生活区",
    "Population": "人口",
    "Skilled diplomats and expert merchants, their curiosity drives them where others hesitate to venture": "熟练的外交官和专家商人，他们的好奇心驱使他们去其他人犹豫冒险的地方",
    "Stone masonry": "砌石",
    "The hard work of cultivating the land always gives its fruits": "耕种土地的辛勤工作总能结出硕果",
    "The quarry is not a place for weak arms": "采石场不是软弱武器的地方",
    "Theresmore's lush forests will help our people prosper": "Theresmore 茂密的森林将帮助我们的人民繁荣发展",
    "We can now build Common house": "我们现在可以建造公共房屋",
    "Wood cutting": "木材切割",
    "Your settlement is starving, produce food!": "你的定居点正在挨饿，生产食物！",
    "Farm": "农场",
    "Farmer": "农民",
    "Farmer food": "农民食品",
    "Food cap": "食物上限",
    "Producing and Crafting": "生产和制作",
    "Storage": "储存",
    "The peasants will feed our great nation": "农民将养活我们伟大的国家",
    "We need more and more material!": "我们需要越来越多的材料！",
    "Your settlement is starving, produce food!": "你的定居点正在挨饿，生产食物！",
    "All your progress will be lost and you'll have to start the game over from the beginning, are you sure you want to continue?": "您的所有进度都将丢失，您必须从头开始游戏，您确定要继续吗？",
    "Ancestor farming": "祖先农业",
    "Cancel": "取消",
    "Confirm": "确认",
    "If you confirm, a deletion of all game data will be performed, do you want to continue?": "如果您确认，将删除所有游戏数据，您要继续吗？",
    "This operation will delete all game data and they will no longer be recoverable, do you confirm you want to continue?": "此操作将删除所有游戏数据且无法恢复，您确定要继续吗？",
    "Archery": "射箭",
    "Army cap": "军帽",
    "Ceramics will allow us to preserve things and will favor the birth of commerce": "陶瓷可以让我们保存东西，并有利于商业的诞生",
    "Lumberjack": "伐木工人",
    "Lumberjack Camp": "伐木工营地",
    "Lumberjack wood": "伐木工木材",
    "Pottery": "陶器",
    "Quarry": "采石场",
    "Quarryman": "采石工",
    "Quarryman stone": "采石场",
    "Stone cap": "石头上限",
    "The bow will allow us to strike from a safe distance": "弓将允许我们从安全距离进行攻击",
    "The quarry will supply the city with stone": "采石场将为城市提供石头",
    "We can now build Lumberjack camp": "我们现在可以建造伐木工人营地",
    "We can now build the Quarry": "我们现在可以建造采石场",
    "Wood cap": "木头上限",
    "Wood is the resource on which we will base our city": "木材是我们建立城市的资源",
    "Unemployed": "未分配",
    "Artisan Workshop": "工匠工作台",
    "Commercial Area": "商业区",
    "A small Village": "一个小村庄",
    "Artisan Workshop": "工匠工作室",
    "Cap Food": "盖帽食品",
    "Cap Wood": "木帽",
    "Commercial Area": "商业区",
    "Crop Rotation": "轮作",
    "Maximum Food Cap": "最大食物上限",
    "Maximum Wood Cap": "最大木帽",
    "Open achievements": "开放成就",
    "Our farmers are learning to farm better and better": "我们的农民正在学习越来越好地耕作",
    "Research points spent": "花费的研究点数",
    "The pleasure of growing grass": "种草的乐趣",
    "Unlocked": "已解锁",
    "Writing": "写作",
    "Your settlement is starting to grow": "您的定居点开始增长",
    "A resourceful warehouse": "资源丰富的仓库",
    "Breeding": "育种",
    "Copper cap": "铜上限",
    "Crop rotation is a fundamental process for keeping fields productive": "轮作是保持田间生产力的基本过程",
    "Fame": "声誉",
    "FAME is a resource you get from the great works or great deeds you will do in Theresmore. At prestige time it will be used to calculate your LEGACY points that will allow you to get permanent bonuses in each of your game runs!": "声誉 是您从在 Theresmore 所做的伟大作品或伟大事迹中获得的资源。 在声望时间，它将用于计算您的 遗产 点数，这将使您在每次游戏运行中获得永久奖励！",
    "Iron cap": "铁上限",
    "Now we can build the Store": "现在我们可以建立 商店",
    "Quarry stone": "采石场",
    "Store": "商店",
    "Verba volant scripta manent": "文字飞扬，文字犹在",
    "We will have to breed the best horses in Theresmore": "我们必须在 Theresmore 培育出最好的马",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "+": "+",
    "s": "s",
    "es": "es",
    "e": "e",
    "o": "o",
    "r": "r",
    "m": "m",
    "v": "v",
    "%": "%",
    "/": "/",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Warning ": "警告 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Your village is empty, look for some new technology": " 你的村庄是空的，寻找一些新技术",
    "We can now build Common house": " 我们现在可以建造普通房屋",
    "Being able to feed the population has always been the biggest problem for early human settlements. We can now build Farm": " 能够养活人口一直是早期人类住区的最大问题。 我们现在可以建立农场",
    "We can now build Lumberjack camp": "  我们现在可以建造伐木工人营地",
    "Your settlement is starving, produce food!": "  你的定居点正在挨饿，生产食物！",
    "We can now build the Quarry": "  我们现在可以建造采石场",
    "Your settlement is starting to grow": "你的定居点开始扩大",
    "Our farmers are learning to farm better and better": "我们的农民正在学习越来越好地耕作",
    "5 Farm : The pleasure of growing grass": "5 农场：种草的乐趣",
    "5 Common House : A small Village": "5 普通房屋：一个小村庄",
    "Now we can build the Store": "现在我们可以建立商店了",
    "FAME is a resource you get from the great works or great deeds you will do in Theresmore. At prestige time it will be used to calculate your LEGACY points that will allow you to get permanent bonuses in each of your game runs!": "FAME 是您从在 Theresmore 所做的伟大作品或伟大事迹中获得的资源。 在声望时，它将用于计算您的 遗产 点数，这将使您在每次游戏运行中获得永久奖励！",
    "Your settlement is starving, produce food!": "你的定居点正在挨饿，生产食物！",
    "Being able to feed the population has always been the biggest problem for early human settlements. We can now build Farm": "能够养活人口一直是早期人类住区的最大问题。 我们现在可以建立农场",
    "By working on the first pieces of craftsmanship, we can create tools. We can build the Artisan workshop": "通过研究第一批工艺，我们可以创造工具。 我们可以建造工匠工作台",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)\s$/,
    /^\+([\d\.]+)\%$/,
    /^\+([\d\.]+)\/s$/,
    /^\-([\d\.]+)\/s$/,
    /^\[([\d\.]+):([\d\.]+)\] $/,
    /^([\d\.]+) \(\-([\d\.]+)\)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Common House$/, '$1 普通房屋'],
    [/^([\d\.,]+) Farm$/, '$1 农场'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);